### ISSUE TITLE
external plugins installation OR RABBITMQ_PLUGINS_EXPAND_DIR not working

### ISSUE THREAD

**Issue by wireless00** [bitnami/bitnami-docker-rabbitmq#100] opened 2019-10-08 13:57 UTC
external plugins installation OR RABBITMQ_PLUGINS_EXPAND_DIR not working. At least to install Prometheus exporter

1- Create new Dockerfile with Bitnami/rabbitmq as the FROM
2- ADD "${prometheusBase}/accept-0.3.5.ez" $RABBITMQ_MNESIA_BASE/$RABBITMQ_NODENAME-plugins-expand
*prometheusBase is correct plugin URL in a variable

Plugin download seem to work correctly as far as Docerbuild is concerned.

**Describe the results you received:**

When trying to run the container image. I get this error:
/librabbitmq.sh: line 181: /opt/bitnami/rabbitmq/.rabbitmq/.erlang.cookie: Permission denied

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

LATEST version of bitname/rabbitmq

Running in Docker on my Mac for testing. Image should end in OpenShift.

**Comment by javsalgar** [comment] 2019-10-09 15:18
Hi,

That's strange. Could you share a Dockerfile that would help us to easily reproduce the issue?

**Comment by hypnoglow** [comment] 2019-10-20 20:18
I had a similar issue when adding plugins by extending the Dockerfile:

```Dockerfile
FROM bitnami/rabbitmq:3.7.15-debian-9-r18

USER root

RUN curl -sSL https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.8.0/rabbitmq_delayed_message_exchange-3.8.0.ez \
    -o /opt/bitnami/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.8.0.ez \
    && rabbitmq-plugins enable rabbitmq_delayed_message_exchange

USER 1001
```

When running this image, the following error occurs:

```bash
/librabbitmq.sh: line 181: /opt/bitnami/rabbitmq/.rabbitmq/.erlang.cookie: Permission denied
```

This is because `rabbitmq-plugins enable` already creates that cookie file. To mitigate this, simply delete that file after enabling the plugin:

```Dockerfile
FROM bitnami/rabbitmq:3.7.15-debian-9-r18

USER root

RUN curl -sSL https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.8.0/rabbitmq_delayed_message_exchange-3.8.0.ez \
    -o /opt/bitnami/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.8.0.ez \
    && rabbitmq-plugins enable rabbitmq_delayed_message_exchange \
    && rm /opt/bitnami/rabbitmq/.rabbitmq/.erlang.cookie

USER 1001
```

In my case, enabling the plugin was not necessary, because I use Kubernetes Helm chart that writes a list of plugins to the `enabled_plugins` file, so I ended up with shorter version of Dockerfile:

```Dockerfile
FROM bitnami/rabbitmq:3.7.15-debian-9-r18

USER root

RUN curl -sSL https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.8.0/rabbitmq_delayed_message_exchange-3.8.0.ez \
    -o /opt/bitnami/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.8.0.ez

USER 1001
```

I hope this helps.

**Comment by marcosbc** [comment] 2019-10-21 06:42
Thanks for sharing @hypnoglow!

In your case it makes sense, since it is advised to run RabbitMQ commands (such as `rabbitmq-plugins enable`) with the same user as the container is going to use.

However, we see that the `/opt/bitnami/rabbitmq/plugins` directory is owned by the root user. We'll look into fixing that so those commands can be run as a non-root user.

**Comment by marcosbc** [comment] 2019-10-21 09:15
Hi, just wanted to let you know that the RabbitMQ `plugins` directory is now writable by non-root users, so you shouldn't need to add a `USER root` line in the Dockerfile anymore for adding the plugin.

With that change, you should not find this issue anymore so I'll close this issue. Feel free to add any comment if you continue with issues.

**Closed by marcosbc** 2019-10-21 09:15 UTC

**Comment by nitrag** [comment] 2019-11-07 14:47
@marcosbc I don't see that

```
docker run -it bitnami/rabbitmq:3.8.1-debian-9-r3 bash
Unable to find image 'bitnami/rabbitmq:3.8.1-debian-9-r3' locally
3.8.1-debian-9-r3: Pulling from bitnami/rabbitmq
3c9020349340: Already exists 
47e9b8e7eee2: Pull complete 
14ed16664f82: Pull complete 
0fd01a09a90c: Pull complete 
99ddde791065: Pull complete 
43dbbaed891c: Pull complete 
c19ddecaab76: Pull complete 
452e7af4745e: Pull complete 
c82bce948a9e: Pull complete 
8619f5c62350: Pull complete 
438e52827746: Pull complete 
Digest: sha256:4138bd07138fa5e1044125889bdf825cce9aade205a23bc50a52d86a7856f0df
Status: Downloaded newer image for bitnami/rabbitmq:3.8.1-debian-9-r3
 14:46:01.00 
 14:46:01.00 Welcome to the Bitnami rabbitmq container
 14:46:01.00 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
 14:46:01.00 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
 14:46:01.01 Send us your feedback at containers@bitnami.com
 14:46:01.01 

I have no name!@d8fb83aaed40:/$ ls -alh /opt/bitnami/rabbitmq/plugins/
total 7.5M
drwxrwxr-x 1 root root 4.0K Nov  1 04:23 .
drwxr-xr-x 1 root root 4.0K Nov  7 13:12 ..
-rw-rw-r-- 1 root root  14K Nov  1 04:06 accept-0.3.5.ez
-rw-rw-r-- 1 root root 108K Nov  1 04:06 amqp10_client-3.8.1.ez
-rw-rw-r-- 1 root root  45K Nov  1 04:06 amqp10_common-3.8.1.ez
-rw-rw-r-- 1 root root 401K Nov  1 04:06 amqp_client-3.8.1.ez
-rw-rw-r-- 1 root root  20K Nov  1 04:06 aten-0.5.2.ez
```

**Comment by rafariossaa** [comment] 2019-11-12 16:17
Hi @nitrag ,
  You can do:
```$ docker run -it bitnami/rabbitmq:3.8.1-debian-9-r3 bash
Unable to find image 'bitnami/rabbitmq:3.8.1-debian-9-r3' locally
3.8.1-debian-9-r3: Pulling from bitnami/rabbitmq
3c9020349340: Already exists 
47e9b8e7eee2: Already exists 
14ed16664f82: Already exists 
0fd01a09a90c: Already exists 
99ddde791065: Already exists 
43dbbaed891c: Pull complete 
c19ddecaab76: Pull complete 
452e7af4745e: Pull complete 
c82bce948a9e: Pull complete 
8619f5c62350: Pull complete 
438e52827746: Pull complete 
Digest: sha256:4138bd07138fa5e1044125889bdf825cce9aade205a23bc50a52d86a7856f0df
Status: Downloaded newer image for bitnami/rabbitmq:3.8.1-debian-9-r3
 16:14:16.36 
 16:14:16.36 Welcome to the Bitnami rabbitmq container
 16:14:16.36 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
 16:14:16.37 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
 16:14:16.37 Send us your feedback at containers@bitnami.com
 16:14:16.37 

I have no name!@9f36a91ef368:/$ touch  /opt/bitnami/rabbitmq/plugins/test
I have no name!@9f36a91ef368:/$ ls -l /opt/bitnami/rabbitmq/plugins/test
-rw-r--r-- 1 1001 root 0 Nov 12 16:15 /opt/bitnami/rabbitmq/plugins/test```

  This issue is already closed, please don't hesitate open a new one if you have any issue.

Thanks forehand
Rafael Rios Saaveedra
