### ISSUE TITLE
Unable to start image on windows 10

### ISSUE THREAD

**Issue by pavbis** [bitnami/bitnami-docker-rabbitmq#64] opened 2018-03-15 22:44 UTC
Hi guys,
first off all thanks for this image and your work.
I'm using it on my working mac and didn't had any problems.
Today I tried to use it on my windows pc but it triggers an error.
Would appreciate any help.

**Here is my output:**
```
$ docker-compose up rabbitmq
symfonyapp_rabbitmq_1 is up-to-date
Attaching to symfonyapp_rabbitmq_1
rabbitmq_1  |
rabbitmq_1  | Welcome to the Bitnami rabbitmq container
rabbitmq_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
rabbitmq_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
rabbitmq_1  | Send us your feedback at containers@bitnami.com
rabbitmq_1  |
rabbitmq_1  | nami    INFO  Initializing rabbitmq
rabbitmq_1  | rabbitm INFO  Creating RabbitMQ System User...
rabbitmq_1  | rabbitm INFO  Setting RabbitMQ environment...
rabbitmq_1  | rabbitm INFO  Starting RabbitMQ node rabbit@localhost...
rabbitmq_1  | rabbitm INFO  Configuring RabbitMQ permissions...
rabbitmq_1  | rabbitm INFO
rabbitmq_1  | rabbitm INFO  ########################################################################
rabbitmq_1  | rabbitm INFO   Installation parameters for rabbitmq:
rabbitmq_1  | rabbitm INFO     Persisted data and properties have been restored.
rabbitmq_1  | rabbitm INFO     Any input specified will not take effect.
rabbitmq_1  | rabbitm INFO   This installation requires no credentials.
rabbitmq_1  | rabbitm INFO  ########################################################################
rabbitmq_1  | rabbitm INFO
rabbitmq_1  | nami    INFO  rabbitmq successfully initialized
rabbitmq_1  | INFO  ==> Starting rabbitmq...
rabbitmq_1  | nami    ERROR Unable to start com.bitnami.rabbitmq: 2018-03-13 20:24:51 Cookie file /opt/bitnami/rabbitmq/.rabbitmq/.erlang.cookie must be accessible by                            owner only
rabbitmq_1  | 2018-03-13 20:24:51 crash_report
rabbitmq_1  |     initial_call:     pid:     registered_name:     error_info:     ancestors:     message_queue_len:     messages:     links:     dictionary:     trap_                           exit:     status:     heap_size:     stack_size:     reductions: 2018-03-13 20:24:51 supervisor_report
rabbitmq_1  |     supervisor:     errorContext:     reason:     offender: 2018-03-13 20:24:51 supervisor_report
rabbitmq_1  |     supervisor:     errorContext:     reason:     offender: 2018-03-13 20:24:51 crash_report
rabbitmq_1  |     initial_call:     pid:     registered_name:     error_info:     ancestors:     message_queue_len:     messages:     links:     dictionary:     trap_                           exit:     status:     heap_size:     stack_size:     reductions: 2018-03-13 20:24:51 std_info
rabbitmq_1  |     application:     exited:     type: Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_chi                           ld,net_sup,{shutdown,{failed_to_start_child,auth,{"Cookie file /opt/bitnami/rabbitmq/.r
rabbitmq_1  |
rabbitmq_1  | Crash dump is being written to: /opt/bitnami/rabbitmq/var/log/rabbitmq/erl_crash.dump...
```

- Output of `docker version`:

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true

```

- Output of `docker info`:

```
Containers: 23
 Running: 3
 Paused: 0
 Stopped: 20
Images: 70
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d3801c9
ID: O67W:36IN:A47Z:HUYV:OYCM:HLP3:Z45C:ZXVA:TSNK:354P:KSP5:26LC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 43
 Goroutines: 54
 System Time: 2018-03-15T22:42:06.0306839Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by juan131** [comment] 2018-03-16 10:28
It looks like a permission issue:

```
rabbitmq_1  | nami    ERROR Unable to start com.bitnami.rabbitmq: 2018-03-13 20:24:51 Cookie file /opt/bitnami/rabbitmq/.rabbitmq/.erlang.cookie must be accessible by                            owner only
```

That directory `/opt/bitnami/rabbitmq/.rabbitmq/` is indeed a symbolic link to `/bitnami/rabbitmq/.rabbitmq/`. `/bitnami/rabbitmq/` is a persisted directory where a volume is mounted. 

You didn't change anything on the `docker-compose.yml` file, did you? By default it's configured to attach a local Docker volume on that directory (more info at: https://docs.docker.com/storage/volumes/) and it seems it's not setting the right permissions...

Could you run the command below to check the permissions?

```
docker-compose exec rabbitmq ls -la /bitnami/rabbitmq/.rabbitmq/
```

**Comment by pavbis** [comment] 2018-03-18 20:41
@juan131  here is my docker-compose.yml for rabbitmq container:

  rabbitmq:
    image: bitnami/rabbitmq:latest
    volumes:
      - ./rabbitmq-persistence:/bitnami/
    ports:
      - "5672:5672"
      - "15672:15672"

I just defined ports and volumes.


And here is the output of docker-compose exec:

$ winpty docker-compose exec rabbitmq bash
root@80f7f1b21e63:/# ls -la /bitnami/rabbitmq/.rabbitmq/
total 5
drwxr-xr-x 2 root root    0 Mar 13 18:20 .
drwxr-xr-x 2 root root 4096 Mar 13 18:21 ..
-r-xr-xr-x 1 root root   32 Mar 13 18:20 .erlang.cookie

**Comment by juan131** [comment] 2018-03-19 09:23
The problem is that `.erlang.cookie` file  has the permissions 555. As you can check the owner, the group and others has read and execution permissions. The error you found is complaining about it since it considers that it should be something like `400` where only the owner can access the file with reading permissions.

The issue is that the logic which starts RabbitMQ cannot set the permissions of the file properly since it's hosted on a Windows Volume. 

See this issue on StackOverFlow:

https://stackoverflow.com/questions/46597290/cant-change-the-permissions-of-files-folders-on-a-volume-with-docker-windows

I think that you won't be able to use mounted volumes on Windows. @tompizmor do you know any workaround for this?

**Comment by pavbis** [comment] 2018-03-20 12:33
@juan131 well, thanks for such a detailed explanation.
So it's a windows related issue, wright?
In that case I would close this issue sinde it's not related to rabbitmq image.

**Comment by juan131** [comment] 2018-03-20 14:03
It's an issue with the permissions when mounting volumes from a Windows host.

Please do to close the issue yet since I would like to read @tompizmor 's opinion about it.

**Comment by carrodher** [comment] 2022-07-28 15:49
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html

**Closed by carrodher** 2022-07-28 15:49 UTC
Labels: on-hold
