### ISSUE TITLE
 BUG REPORT INFORMATION Connections high memory usage

### ISSUE THREAD

**Issue by kvitajakub** [bitnami/bitnami-docker-rabbitmq#50] opened 2017-06-28 21:03 UTC
**Description**
I deployed latest release with helm chart on Kubernetes and I am seeing high memory usage for connections/exchanges even without messages. Looks like >10MB per connection. With 100 connections I am at 1.2GB memory with peak at 1.5GB.

With my old nondocker nonbitnami setup I don't see any of this. 100 connections take around 40MB of memory.

Here is example of memory usage with 30 connections/exchanges and no messages sent.
![screenshot from 2017-06-28 16-29-52](https://user-images.githubusercontent.com/1778140/27659998-7796a688-5c23-11e7-9f9e-75d5ce89cf6b.png)

Anybody seeing similar issues?

**Steps to reproduce the issue:**

1. Get Kubernetes cluster.
2. Install with Helm: `helm install --name rabbitmq --set image=bitnami/rabbitmq:3.6.10-r2 stable/rabbitmq`
3. Create connections.

**Describe the results you received:**
With no messages sent, memory usage goes up rapidly. 

**Describe the results you expected:**
Memory usage keeps around 50-100MB with regular usage.

**Additional information you deem important (e.g. issue happens only occasionally):**

Release `bitnami/rabbitmq:3.6.10-r0` with the same setup wasn't freeing the memory and erroring eventually.

**Version**

- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

I'm running 8-node Kubernetes cluster on AWS.

**Comment by jbianquetti-nami** [comment] 2017-07-03 16:11
Hi, @kvitajakub . 

I've done a quick test and I'm not able to reproduce your issue.  I will try to replicate your setup  as close as possible, but I need to know how you created the connections (clients used, versions, ...) 
Also, which kind of EC2 instance is supporting the workload?  

Please, let me know this information in order to be able to reproduce your environment as close as possible.

**Comment by kvitajakub** [comment] 2017-07-05 16:55
Hi, @jbianquetti-nami .
After creating this issue I tried running official [RabbitMQ image](https://hub.docker.com/_/rabbitmq/). But I saw the same problem. It could be issue with my client, but I didn't find anything about that.

Kubernetes cluster:
3 masters (m3.medium)
5 nodes (t2.medium)
Installed with Kops.

Client:
Ruby/Rails 4.2.3 -> sneakers 2.5.0 -> bunny 2.6.6

Server:
`bitnami/rabbitmq:3.6.10-r2`  (I tried multiple images from bitnami and official releases and no change anywhere)


I also have an old RabbitMQ running on EC2 instance (t2.medium) which was deployed almost 2 years ago (RabbitMQ 3.5.2, Erlang R14B04). When I connect to it with the same client (~30 connections, no messages), memory usage is drastically lower:
![screenshot from 2017-07-05 12-53-49](https://user-images.githubusercontent.com/1778140/27875419-09afc952-6181-11e7-9ae8-e9bfe01bf4fe.png)

**Comment by listingmirror** [comment] 2017-07-11 11:31
FWIW I am on the GKE with the latest docker image. I have 631 connections right now and almost no memory usage.

![image](https://user-images.githubusercontent.com/19509188/28066395-c6b869b8-660a-11e7-817a-120bf74381f2.png)

Now my CPU usage is a mess, I am burning 1 cpu 100% at idle.. that is my project. I would gladly trade you some memory for some CPU back.

**Comment by kvitajakub** [comment] 2017-07-11 14:11
@listingmirror True, thats bad.
What client you're using?

**Comment by listingmirror** [comment] 2017-07-11 14:19
@kvitajakub amqp, which I think is my only choice for Celery + Python 3.6

**Comment by jbianquetti-nami** [comment] 2017-07-11 15:34
I've taken a look at Sneakers and it explicitly states: 

> By default, each worker will open its own connection to RabbitMQ. With a larger number of workers, this is suboptimal.
> 
> It is possible to make Sneakers use a provided Bunny connection and
> this connection will be shared by all workers.
https://github.com/jondot/sneakers/wiki/Configuration#rabbitmq-connections

So take care of using Bunny right, use the latest version and set `:share_bunny_connection`.  Otherwise, it seems defaults to 1:1.

**Comment by kvitajakub** [comment] 2017-07-11 18:02
Thank you, I didn't notice that. I tried it with the shared connection and it definitely helps lower the memory usage.

However I still see the issue. I had 6 connection (each with 5 channels) and memory usage around 235MB.  Same thing as I described before.

**Comment by silviofdez** [comment] 2017-07-19 11:41
Hi, did you try to use a different client? Just to testing purposes.

**Comment by kvitajakub** [comment] 2017-07-20 15:02
Hey, no I didn't but other people tried it. This seems like my client issue though.

**Comment by silviofdez** [comment] 2017-07-20 15:52
As it see like a client issue I am going to close this issue. Thank you for the feedback.

**Closed** 2017-07-20 15:52 UTC
