### ISSUE TITLE
enable management console/ui

### ISSUE THREAD

**Issue by magicalbanana** [bitnami/bitnami-docker-rabbitmq#56] opened 2017-11-03 20:26 UTC
**Description**

How do we access the management console? Is it enabled by default? Or I need to enable it?

**Comment by juan131** [comment] 2017-11-14 11:22
As you can check in the `Environment variables section` of the README:

```
RABBITMQ_MANAGER_PORT_NUMBER: Manager port. Default: 15672
```

By default the Manager Panel can be accessed through the port **15672**. Therefore, once you have your server up and running, you can run the command below to obtain the IP of the container:

```
docker inspect CONTAINER_NAME | grep "IPAddress"
```

Once you obtain the IP, open a browser and go to: http://CONTAINER-IP:15672/

**Comment by zotona** [comment] 2018-03-26 09:56
management plugin doesnt work at latest tag.

**Comment by juan131** [comment] 2018-03-26 10:45
Hi @zotona 

I was unable to reproduce it. I just created a RabbitMQ container using `docker-compose.yaml` (which uses "latest" image) and then I accessed locally to http://127.0.0.1:15672

I could login without any issue on the Management Panel... Could you please provide more info about how to reproduce the issue?

**Comment by mkp15** [comment] 2018-12-12 23:31
I am also not able to access management console. 
Env: Mac
Image: bitnami/rabbitmq:latest
docker inspect info
"Gateway": "172.17.0.1",
"IPAddress": "172.17.0.2"
"RABBITMQ_MANAGER_PORT_NUMBER=15672",
"RABBITMQ_NODE_NAME=rabbit@localhost",
"RABBITMQ_NODE_PORT_NUMBER=5672"

so i think console link ( http://172.17.0.2:15672) should be this but it does not open

**Comment by juan131** [comment] 2018-12-13 08:15
There's a known networking bug with Docker and MacOS: https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds

Therefore, you can't access to http://172.17.0.2:15672

**Comment by mkp15** [comment] 2018-12-13 23:05
Thanks, yes that was the issue. After setting the port forwarding, it works fine

**Comment by juan131** [comment] 2018-12-14 08:36
Great @mkp15 !!! I'm glad you could solve the issue!

I proceed to close the issue, feel free to reopen it if you need further assistance.

**Closed by juan131** 2018-12-14 08:36 UTC
Labels: question
